name: Cypress Tests

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm run dev
          config: pageLoadTimeout=100000,baseUrl=http://localhost:3000
        env:
         NODE_PRISMIC_API: ${{ secrets.NODE_PRISMIC_API }}
