name: e2e Tests CI

on: [pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          start: npm run dev
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
        env:
          FF_ENVIRONMENT: development
          NODE_PRISMIC_API: ${{ secrets.NODE_PRISMIC_API }}
          CI: true
