name: e2e Tests CI

on: [pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          start: npm run build && npm start
          wait-on: 'http://localhost:3000'
          browser: chrome
          headless: true
